import { DEFAULT_AGENT_MAX_ITERATIONS, type OrbitConfig } from "./schema.js";

export const DEFAULT_CONFIG: OrbitConfig = {
  schemaVersion: 1,
  name: "orbit-project",
  editor: "notepad.exe",
  autoCommit: false,
  language: "en",
  security: {
    trustProjectExecutables: false,
    encryptCheckpoints: true,
  },
  provider: {
    default: "deepseek",
  },
  models: {
    default: "deepseek-v4-flash",
    fast: "deepseek-v4-flash",
    planner: "deepseek-v4-pro",
    coder: "deepseek-v4-pro",
    reviewer: "deepseek-v4-pro",
    summarizer: "deepseek-v4-flash",
    embedding: "text-embedding-3-small",
  },
  providers: {
    deepseek: {
      type: "deepseek",
      baseUrl: "https://api.deepseek.com",
      apiKeyEnv: "DEEPSEEK_API_KEY",
      deepSeekApiFormat: "auto",
      requestTimeoutMs: 45_000,
      streamTimeoutMs: 300_000,
      totalTimeoutMs: 660_000,
      maxRetries: 0,
      models: ["deepseek-v4-flash", "deepseek-v4-pro"],
    },
    tokendance: {
      type: "openai-compatible",
      baseUrl: "https://tokendance.space/gateway/v1",
      apiKeyEnv: "TOKENDANCE_API_KEY",
      deepSeekApiFormat: "chat-completions",
      models: ["deepseek-v4-flash", "deepseek-v4-pro"],
    },
    openai: {
      type: "openai",
      baseUrl: "https://api.openai.com/v1",
      apiKeyEnv: "OPENAI_API_KEY",
      models: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano"],
    },
    anthropic: {
      type: "anthropic",
      baseUrl: "https://api.anthropic.com",
      apiKeyEnv: "ANTHROPIC_API_KEY",
      models: [
        "claude-fable-5",
        "claude-opus-4-8",
        "claude-sonnet-4-6",
        "claude-haiku-4-5",
      ],
    },
    ollama: {
      type: "ollama",
      baseUrl: "http://localhost:11434",
    },
  },
  permissions: {
    mode: "normal",
    allowRead: true,
    requireApprovalForWrite: true,
    requireApprovalForBash: true,
    blockDangerousCommands: true,
    protectSecrets: true,
    protectedPaths: [
      ".env",
      ".env.*",
      ".git/**",
      ".orbit/**",
      ".npmrc",
      ".pypirc",
      ".netrc",
      "id_rsa",
      "id_ed25519",
      ".ssh/**",
      ".gnupg/**",
      ".aws/**",
      ".azure/**",
      ".config/gcloud/**",
      ".kube/**",
      "**/*.{key,pem,p12,pfx}",
      "**/*secret*",
      "**/*token*",
      "**/*credential*",
    ],
  },
  context: {
    maxFilesToIndex: 5000,
    maxFileSizeKb: 512,
    autoCodebaseRetrieval: true,
    ignore: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.git/**",
      "**/coverage/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/AppData/**",
      "**/Local Settings/**",
      "**/Downloads/**",
      "**/Documents/**",
      "**/Pictures/**",
      "**/Music/**",
      "**/Videos/**",
      "**/.npm/**",
      "**/.cargo/**",
      "**/.gradle/**",
      "**/.rustup/**",
      "**/.orbit/**",
    ],
    autoCompact: true,
    compactThreshold: 0.75,
    autoRepair: false,
    maxRepairAttempts: 3,
    testCommands: [],
  },
  agent: {
    // Long enough for complete document, migration, and verification
    // workflows. Normal modes retain periodic consent; Full Access continues
    // checkpoints without interruption. Progress and budget guards still
    // bound unhealthy runs.
    maxIterations: DEFAULT_AGENT_MAX_ITERATIONS,
    fastMaxOutputTokens: 32768,
    maxOutputTokens: 16384,
    teamPreset: "balanced",
    maxReviewAttempts: 3,
    maxReviewConcurrency: 2,
  },
  agents: {
    enabled: true,
    directories: [
      ".agents/agents",
      ".orbit/agents",
      ".claude/agents",
      "~/.orbit/agents",
      "~/.claude/agents",
    ],
    maxProfiles: 32,
  },
  tools: {
    bash: {
      enabled: true,
      timeoutMs: 120000,
    },
    backgroundTasks: {
      maxConcurrentTasks: 8,
      maxRetainedTasks: 64,
      maxOutputBytes: 1024 * 1024,
      terminateGraceMs: 2_000,
      awaitOnCompletion: true,
      completionWaitMs: 30_000,
    },
    webSearch: {
      enabled: true,
      provider: "auto",
      searxngUrls: [],
      tavilyApiKeyEnv: "TAVILY_API_KEY",
      tavilyBaseUrl: "https://api.tavily.com/search",
      timeoutMs: 8000,
      maxResults: 8,
    },
    mcp: {
      enabled: false,
    },
  },
  skills: {
    enabled: true,
    directories: [
      ".orbit/skills",
      ".agents/skills",
      ".claude/skills",
      "~/.claude/skills",
      "~/.orbit/skills",
      "@orbit/builtin-skills",
    ],
    activation: "auto",
    maxActive: 3,
    disabled: [],
    maxSkillBytes: 24000,
    maxAutoSkillBytes: 8000,
  },
  mcpServers: {},
  hooks: {},
  pricing: {
    "deepseek-v4-flash": {
      inputCostPer1M: 0.14,
      outputCostPer1M: 0.28,
      cacheReadCostPer1M: 0.0028,
      scheduled: {
        effectiveAt: "2026-08-16T16:00:00Z",
        peakHoursUtc: ["01:00-04:00", "06:00-10:00"],
        peak: {
          inputCostPer1M: 0.44,
          outputCostPer1M: 1.32,
          cacheReadCostPer1M: 0.014,
        },
        offPeak: {
          inputCostPer1M: 0.22,
          outputCostPer1M: 0.66,
          cacheReadCostPer1M: 0.007,
        },
      },
    },
    "deepseek-v4-pro": {
      inputCostPer1M: 0.435,
      outputCostPer1M: 0.87,
      cacheReadCostPer1M: 0.003625,
      scheduled: {
        effectiveAt: "2026-08-16T16:00:00Z",
        peakHoursUtc: ["01:00-04:00", "06:00-10:00"],
        peak: {
          inputCostPer1M: 1.32,
          outputCostPer1M: 3.96,
          cacheReadCostPer1M: 0.044,
        },
        offPeak: {
          inputCostPer1M: 0.66,
          outputCostPer1M: 1.98,
          cacheReadCostPer1M: 0.022,
        },
      },
    },
  },
  budgetLimit: 10.0,
  session: {
    store: "jsonl",
    path: ".orbit/sessions",
  },
  autocomplete: {
    enabled: true,
    provider: "ollama",
    model: "qwen2.5-coder:1.5b",
    debounceMs: 150,
  },
  tui: {
    mouse: true,
    scrollSpeed: 50,
  },
};
