import type { WebUiLanguage } from "./WebUiPage.js";

/** Browser chrome only. Website HTML never enters Orbit's authenticated document. */
export function renderBrowserPreview(
  language: WebUiLanguage,
  icon: (name: "panel" | "close" | "explain") => string,
): string {
  const t = (en: string, zh: string, tw: string) =>
    language === "en" ? en : language === "zh-TW" ? tw : zh;
  const searchPreference = `<div class="browser-search-preference"><label for="browserSearchEngine">${t("Search with", "搜索引擎", "搜尋引擎")}</label><select id="browserSearchEngine"><option value="bing">Bing</option><option value="google">Google</option><option value="baidu">${t("Baidu", "百度", "百度")}</option><option value="duckduckgo">DuckDuckGo</option></select></div>`;
  const findBar = `<form id="browserFindBar" class="browser-find-bar" role="search" hidden><label class="sr-only" for="browserFindQuery">${t("Find in page", "在网页中查找", "在網頁中尋找")}</label><input id="browserFindQuery" type="search" maxlength="200" autocomplete="off" spellcheck="false" placeholder="${t("Find in page", "在网页中查找", "在網頁中尋找")}" /><span id="browserFindStatus" role="status" aria-live="polite"></span><button id="browserFindPrevious" class="icon-button" type="button" aria-label="${t("Previous match", "上一个匹配项", "上一個符合項目")}">↑</button><button id="browserFindNext" class="icon-button" type="submit" aria-label="${t("Next match", "下一个匹配项", "下一個符合項目")}">↓</button><button id="browserFindClose" class="icon-button" type="button" aria-label="${t("Close find", "关闭查找", "關閉尋找")}">${icon("close")}</button></form>`;
  const pageReader = `<section class="browser-page-reader" id="browserPageReader" role="dialog" aria-modal="false" aria-labelledby="browserPageReaderTitle" hidden><header><h3 id="browserPageReaderTitle">${t("Page outline", "网页文本纲要", "網頁文字綱要")}</h3><span class="browser-page-reader-pan-hint">${t("Shift + scroll to pan page", "Shift + 滚轮平移网页", "Shift + 滾輪平移網頁")}</span><button class="icon-button" id="browserPageReaderClose" type="button" aria-label="${t("Close page outline", "关闭网页纲要", "關閉網頁綱要")}">${icon("close")}</button></header><p id="browserPageReaderStatus" role="status" aria-live="polite"></p><div id="browserPageReaderText" role="document" tabindex="0" aria-label="${t("Current page text outline", "当前网页文本纲要", "目前網頁文字綱要")}"></div><section class="browser-page-reader-controls" id="browserPageReaderControls" aria-labelledby="browserPageReaderControlsTitle" hidden><h4 id="browserPageReaderControlsTitle">${t("Page controls", "网页控件", "網頁控制項")}</h4><div id="browserPageReaderControlList" role="list"></div></section><footer><span>${t("Current-page snapshot · up to 16,000 characters · first 60 visible controls", "当前网页快照 · 最多 16000 字符 · 前 60 个可见控件", "目前網頁快照 · 最多 16000 字元 · 前 60 個可見控制項")}</span><button class="text-button" id="browserPageReaderRefresh" type="button">${t("Refresh outline", "刷新纲要", "重新整理綱要")}</button></footer></section>`;
  const selectPopup = `<section class="browser-select-popup" id="browserSelectPopup" role="dialog" aria-modal="false" aria-labelledby="browserSelectTitle" hidden><header><h3 id="browserSelectTitle"></h3><button class="icon-button" id="browserSelectClose" type="button" aria-label="${t("Close page options", "关闭网页选项", "關閉網頁選項")}">${icon("close")}</button></header><label class="sr-only" for="browserSelectSearch">${t("Search page options", "搜索网页选项", "搜尋網頁選項")}</label><input id="browserSelectSearch" type="search" autocomplete="off" spellcheck="false" placeholder="${t("Search options…", "搜索选项…", "搜尋選項…")}" /><div id="browserSelectOptions" class="browser-select-options" role="listbox" aria-label="${t("Page options", "网页选项", "網頁選項")}"></div><p class="browser-select-empty" id="browserSelectEmpty" hidden>${t("No matching options", "没有匹配的选项", "沒有符合的選項")}</p><footer><span id="browserSelectStatus" role="status" aria-live="polite"></span><div><button class="text-button" id="browserSelectPrevious" type="button">${t("Previous", "上页", "上一頁")}</button><button class="text-button" id="browserSelectNext" type="button">${t("Next", "下页", "下一頁")}</button></div></footer></section>`;
  const inputPicker = `<section class="browser-select-popup browser-native-picker" id="browserPickerPopup" role="dialog" aria-modal="false" aria-labelledby="browserPickerTitle" aria-describedby="browserPickerHelp" hidden><header><h3 id="browserPickerTitle"></h3><button class="icon-button" id="browserPickerClose" type="button" aria-label="${t("Close website picker", "关闭网页选择器", "關閉網頁選擇器")}">${icon("close")}</button></header><label class="sr-only" for="browserPickerValue">${t("New value for website control", "网页控件的新值", "網頁控制項的新值")}</label><input id="browserPickerValue" type="date" /><p id="browserPickerHelp">${t("Choose a new value. The current value stays on the page until you apply it.", "选择新值；点击应用前，网页上的当前值不会改变。", "選擇新值；按下套用前，網頁上的目前值不會改變。")}</p><p id="browserPickerStatus" role="status" aria-live="polite"></p><footer><button class="text-button" id="browserPickerClear" type="button">${t("Clear value", "清除值", "清除值")}</button><div><button class="text-button" id="browserPickerCancel" type="button">${t("Cancel", "取消", "取消")}</button><button class="secondary-button" id="browserPickerApply" type="button">${t("Apply to page", "应用到网页", "套用到網頁")}</button></div></footer></section>`;
  const uploadPopup = `<section class="browser-select-popup browser-upload-popup" id="browserUploadPopup" role="dialog" aria-modal="false" aria-labelledby="browserUploadTitle" aria-describedby="browserUploadHelp" hidden><header><h3 id="browserUploadTitle">${t("Website file request", "网页请求文件", "網頁要求檔案")}</h3><button class="icon-button" id="browserUploadClose" type="button" aria-label="${t("Cancel file request", "取消文件请求", "取消檔案要求")}">${icon("close")}</button></header><p id="browserUploadHelp">${t("Choose files on your computer. Only files you apply are sent to this website (up to 8 files, 32 MB total).", "从电脑选择文件。只有点击“上传到网页”后才会发送给此网站（最多 8 个文件，总计 32 MB）。", "從電腦選擇檔案。只有按下「上傳到網頁」後才會傳送給此網站（最多 8 個檔案，合計 32 MB）。")}</p><label for="browserUploadFiles">${t("Files", "文件", "檔案")}</label><input id="browserUploadFiles" type="file" /><p id="browserUploadStatus" role="status" aria-live="polite"></p><footer><button class="text-button" id="browserUploadCancel" type="button">${t("Cancel", "取消", "取消")}</button><button class="secondary-button" id="browserUploadApply" type="button" disabled>${t("Upload to website", "上传到网页", "上傳到網頁")}</button></footer></section>`;
  const downloadPopup = `<section class="browser-select-popup browser-download-popup" id="browserDownloadPopup" role="dialog" aria-modal="false" aria-labelledby="browserDownloadTitle" aria-describedby="browserDownloadHelp" hidden><header><h3 id="browserDownloadTitle">${t("Website download", "网页下载", "網頁下載")}</h3><button class="icon-button" id="browserDownloadClose" type="button" aria-label="${t("Discard download", "放弃下载", "捨棄下載")}">${icon("close")}</button></header><p id="browserDownloadName"></p><p id="browserDownloadHelp">${t("Save only if you trust this file. Orbit does not put it in your project. Maximum 64 MB.", "仅在信任文件时保存。Orbit 不会将它放进项目目录。上限 64 MB。", "僅在信任檔案時儲存。Orbit 不會將它放進專案目錄。上限 64 MB。")}</p><p id="browserDownloadStatus" role="status" aria-live="polite"></p><footer><button class="text-button" id="browserDownloadDiscard" type="button">${t("Discard", "放弃", "捨棄")}</button><button class="secondary-button" id="browserDownloadSave" type="button" disabled>${t("Save file", "保存文件", "儲存檔案")}</button></footer></section>`;
  return `<section class="browser-preview-panel browser-live-panel" id="browserPreviewPanel" role="tabpanel" aria-labelledby="browserTab" hidden tabindex="-1">
    <div class="browser-live-tabs"><div id="browserTabs" role="tablist" aria-label="${t("Browser tabs", "浏览器标签页", "瀏覽器分頁")}"></div><button id="browserNewTab" type="button" class="icon-button" aria-label="${t("New tab", "新标签页", "新增分頁")}">+</button></div>
    <form id="browserPreviewConnect" class="browser-preview-connect"><button type="button" class="icon-button" id="browserBack" aria-label="${t("Back", "后退", "返回")}" title="Alt + ←">←</button><button type="button" class="icon-button" id="browserForward" aria-label="${t("Forward", "前进", "前進")}" title="Alt + →">→</button><button type="button" class="icon-button" id="browserPreviewReload" aria-label="${t("Reload page", "刷新页面", "重新載入")}" title="${t("Reload page", "刷新页面", "重新載入")}">↻</button><div class="browser-preview-address"><label class="sr-only" for="browserPreviewUrl">${t("Search or enter a website", "搜索或输入网址", "搜尋或輸入網址")}</label><input id="browserPreviewUrl" type="text" placeholder="${t("Search or enter a website", "搜索或输入网址", "搜尋或輸入網址")}" aria-describedby="browserSearchDestination" maxlength="4096" autocomplete="off" spellcheck="false" /><span id="browserSearchDestination" class="browser-search-destination">${t("Search: Bing", "搜索：Bing", "搜尋：Bing")}</span></div><button id="browserPreviewStart" class="secondary-button" type="submit">${t("Go", "访问", "開啟")}</button><button id="browserPageActions" class="icon-button" type="button" aria-label="${t("Page actions", "网页操作", "網頁操作")}" aria-haspopup="menu" aria-controls="browserPageContextMenu" aria-expanded="false" title="${t("Page actions · right-click page", "网页操作 · 也可在页面右键", "網頁操作 · 也可在頁面按右鍵")}">⋯</button></form>
    <div class="browser-preview-notice" id="browserPreviewNotice" hidden><div role="alert"><strong id="browserPreviewErrorTitle"></strong><p id="browserPreviewError"></p></div><div class="browser-preview-notice-actions"><button class="text-button" id="browserPreviewChangeEngine" type="button" hidden>${t("Change search engine", "更换搜索引擎", "更換搜尋引擎")}</button><button class="secondary-button" id="browserPreviewRetry" type="button">${t("Retry", "重试", "重試")}</button></div></div>
    <div class="browser-preview-canvas browser-live-canvas">${findBar}<aside class="browser-idle-notice" id="browserIdleNotice" hidden><div role="status" aria-live="polite"><strong id="browserIdleTitle"></strong><p id="browserIdleText"></p></div><button class="secondary-button" id="browserIdleAction" type="button"></button></aside><div class="browser-preview-stage" id="browserPreviewStage" tabindex="0" role="region" aria-label="${t("Interactive web page", "可交互网页", "可互動網頁")}" aria-describedby="browserPreviewPageTitle browserInteractionHint"><div class="browser-preview-empty" id="browserPreviewEmpty"><span class="browser-preview-empty-icon">${icon("explain")}</span><h3>${t("The web, right beside your work.", "在工作台里，直接浏览。", "在工作台裡，直接瀏覽。")}</h3><p>${t("Enter a website or search above. Click, type and scroll right here.", "输入网址或搜索词。直接点击、输入和滚动。", "輸入網址或搜尋詞。直接點擊、輸入與捲動。")}</p><span class="browser-preview-empty-note">${t("Independent session · no personal browser profile", "独立会话 · 不读取个人浏览器资料", "獨立工作階段 · 不讀取個人瀏覽器資料")}</span></div><img id="browserPreviewImage" alt="${t("Interactive browser page", "可交互浏览器页面", "可互動瀏覽器頁面")}" hidden draggable="false" /><textarea id="browserPageInput" aria-label="${t("Type into the web page. Escape returns to browser controls.", "输入到网页，按 Escape 返回浏览器工具栏。", "輸入到網頁，按 Escape 返回瀏覽器工具列。")}" tabindex="-1" autocomplete="off" autocapitalize="off" spellcheck="false"></textarea></div><span class="browser-preview-working" id="browserPreviewWorking" hidden>${t("Loading page…", "正在加载网页…", "正在載入網頁…")}</span>${pageReader}<div class="browser-live-dialog-backdrop" id="browserPageDialogBackdrop" aria-hidden="true" hidden></div></div>
    ${selectPopup}
    ${inputPicker}
    ${uploadPopup}
    ${downloadPopup}
    <div class="browser-page-context-menu" id="browserPageContextMenu" role="menu" aria-label="${t("Page actions", "网页操作", "網頁操作")}" hidden><button id="browserFindPage" type="button" role="menuitem">${t("Find in page", "在网页中查找", "在網頁中尋找")}</button><button id="browserReadPage" type="button" role="menuitem">${t("Read page outline", "阅读网页纲要", "閱讀網頁綱要")}</button><button id="browserCopySelection" type="button" role="menuitem">${t("Copy selected text", "复制所选文字", "複製所選文字")}</button><button id="browserCopyAddress" type="button" role="menuitem">${t("Copy page address", "复制网页地址", "複製網頁網址")}</button></div>
    <section class="browser-live-dialog" id="browserPageDialog" role="dialog" aria-modal="false" aria-labelledby="browserDialogTitle" aria-describedby="browserDialogMessage" hidden><h3 id="browserDialogTitle">${t("Website dialog", "网页对话框", "網頁對話方塊")}</h3><p id="browserDialogMessage"></p><input id="browserDialogInput" class="field-control" maxlength="4000" aria-label="${t("Website dialog response", "网页对话框回复", "網頁對話方塊回覆")}" /><div><button id="browserDialogDismiss" type="button" class="text-button">${t("Cancel", "取消", "取消")}</button><button id="browserDialogAccept" type="button" class="secondary-button">${t("Confirm", "确认", "確認")}</button></div></section>
    <div class="sr-only"><span id="browserPreviewPageTitle">${t("Live browser", "实时浏览器", "即時瀏覽器")}</span><span id="browserInteractionHint">${t("Press Enter to type on the page. Escape returns to browser controls. Page actions opens a readable outline.", "按 Enter 在网页中输入，按 Escape 返回浏览器工具栏；从“网页操作”可打开文本纲要。", "按 Enter 在網頁中輸入，按 Escape 返回瀏覽器工具列；從「網頁操作」可開啟文字綱要。")}</span></div>
    <footer class="browser-preview-footer"><span id="browserPreviewStatus" class="browser-preview-status" role="status"></span><details class="browser-preview-help"><summary>${t("Browser settings & privacy", "浏览设置与隐私", "瀏覽設定與隱私")}</summary><div class="browser-settings-popover">${searchPreference}<p>${t("Real Chromium, with an independent temporary session. Queries go only to your selected search engine when submitted. You and the Agent share the active tab; Agent operations still require normal tool permissions. Local services must be explicitly opened. Website file requests require your selection and confirmation (8 files, 32 MB total). Website downloads require confirmation (64 MB maximum) and save through your browser, not into the project. Extensions and audio are not available. Close clears tabs and cookies; idle sessions close after 30 minutes.", "真实 Chromium，使用独立临时会话。仅在提交时向所选引擎发送搜索词。你与 Agent 共用当前标签页，Agent 操作仍受工具权限约束。本地服务需明确打开。网页请求文件时，须由你选择并确认（最多 8 个，总计 32 MB）。网页下载须确认（上限 64 MB），通过你的浏览器保存，不写入项目。暂不支持扩展和音频。关闭会清除页面和 Cookie；闲置 30 分钟自动关闭。", "真實 Chromium，使用獨立暫存工作階段。僅在送出時向所選引擎傳送搜尋詞。你與 Agent 共用目前分頁，Agent 操作仍受工具權限限制。本機服務須明確開啟。網頁要求檔案時，須由你選擇並確認（最多 8 個，合計 32 MB）。網頁下載須確認（上限 64 MB），透過你的瀏覽器儲存，不寫入專案。暫不支援擴充功能與音訊。關閉會清除分頁和 Cookie；閒置 30 分鐘自動關閉。")}</p></div></details><button type="button" class="text-button" id="browserPreviewStop">${t("Close browser", "关闭浏览器", "關閉瀏覽器")}</button><button type="button" class="secondary-button" id="browserPreviewAsk">${t("Use browser in question", "提问时使用浏览器", "提問時使用瀏覽器")}</button></footer>
  </section>`;
}
